# Generated by Django 4.2.16 on 2024-11-08 15:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('author', 'post')},
        ),
    ]
