# Generated by Django 4.2.16 on 2024-11-13 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_category_tag_post_category_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
